### ISSUE TITLE
Cannot read property 'lib' of undefined (first attempt to run app after install)

### ISSUE THREAD

**Issue by tnwo** [dandv/meteor-crypto-sha1#1]
W20140524-14:40:54.322(1)? (STDERR) /Users/jamesbrooke/.meteor/tools/6f23056589/lib/node_modules/fibers/future.js:173
W20140524-14:40:54.322(1)? (STDERR) 						throw(ex);
W20140524-14:40:54.323(1)? (STDERR) 						      ^
W20140524-14:40:54.327(1)? (STDERR) TypeError: Cannot read property 'lib' of undefined
W20140524-14:40:54.327(1)? (STDERR)     at Package (packages/crypto-sha1/sha1.js:10)
W20140524-14:40:54.327(1)? (STDERR)     at Package (packages/crypto-sha1/sha1.js:136)
W20140524-14:40:54.328(1)? (STDERR)     at packages/crypto-sha1.js:154:4
W20140524-14:40:54.328(1)? (STDERR)     at packages/crypto-sha1.js:161:3
W20140524-14:40:54.328(1)? (STDERR)     at /Users/jamesbrooke/dev/CM-production/.meteor/local/build/programs/server/boot.js:155:10
W20140524-14:40:54.329(1)? (STDERR)     at Array.forEach (native)
W20140524-14:40:54.329(1)? (STDERR)     at Function._.each._.forEach (/Users/jamesbrooke/.meteor/tools/6f23056589/lib/node_modules/underscore/underscore.js:79:11)
W20140524-14:40:54.329(1)? (STDERR)     at /Users/jamesbrooke/dev/CM-production/.meteor/local/build/programs/server/boot.js:82:5

**Comment by dandv** [comment]
Now that Meteor 1.3+ supports npm packages natively, I'll be deleting this repo.
